# Define the C compiler to use
CC=gcc

# Define any compile-time flags
CFLAGS=-Wall

# Define the target executable name
TARGET=scheduler

all:
	$(CC) Isak_testFS.c Isak_libFS.c -o testFS

clean:
	rm -f testFS


